### PR TITLE
Add android build support

### PR DESCRIPTION
**Pull request by minkcrypto-zz**
TO-DO

- [ ] Fix tests
- [x] Change produced .apk name to ElectrumCPU-*
- [ ] **Publish to Play Store**

[ElectrumCPU-3.3.8.0-release.zip](https://github.com/cpuchain/electrum-cpu/files/3390324/ElectrumCPU-3.3.8.0-release.zip)

Very slow on initialization but it works!

cc @y-chan

### CODE REVIEW

**Comment by y-chan** [comment]
I confirmed that the Android binary works.
I will fix the test, but it will take time.

**Review by y-chan — COMMENTED** [review]
confirmd

**Comment by minkcrypto-zz** [comment]
Logo fixed, all we need to do is to fix tests 💪

**Comment by y-chan** [comment]
Oh, very good!

**Pull request merged**
